from __future__ import annotations

from typing import Any

MARKET_TOTALS = {
    "total_listings": 523_847,
    "new_cars": 77_020,
    "under_one_year": 181_310,
    "rare_models": 1_007,
}

COMMON_MISSING_REGIONS = [
    "Казань",
    "Екатеринбург",
    "Краснодар",
    "Ростов-на-Дону",
    "Новосибирск",
    "Самара",
    "Сочи",
    "Уфа",
    "Нижний Новгород",
    "Пермь",
    "Красноярск",
    "Челябинск",
    "Тюмень",
    "Иркутск",
    "Омск",
    "Воронеж",
    "Калининград",
    "Хабаровск",
    "Тула",
    "Киров",
    "Томск",
]

RARE_CARS: list[dict[str, Any]] = [
    {
        "id": "hongqi-e-hs9-flagship",
        "brand": "Hongqi",
        "model": "E-HS9 Flagship",
        "full_name": "Hongqi E-HS9 Flagship",
        "year": 2024,
        "platform": "Auto.ru",
        "price": 12_500_000,
        "listings": 4,
        "sellers": 3,
        "regions_count": 2,
        "regions_present": ["Москва", "Санкт-Петербург"],
        "regions_missing": COMMON_MISSING_REGIONS,
        "competition": "Низкая",
        "deficit": "Высокий",
        "recommendation": "Критический дефицит",
        "market_share": 0.0019,
        "opportunity_tag": "Критический дефицит",
        "segment": "Люкс",
        "body_type": "Внедорожник",
        "condition": "Новый",
        "price_history": [
            {"month": "Окт", "value": 12.9},
            {"month": "Ноя", "value": 12.8},
            {"month": "Дек", "value": 12.7},
            {"month": "Янв", "value": 12.6},
            {"month": "Фев", "value": 12.5},
            {"month": "Мар", "value": 12.5},
        ],
        "listings_history": [
            {"month": "Окт", "value": 6},
            {"month": "Ноя", "value": 5},
            {"month": "Дек", "value": 5},
            {"month": "Янв", "value": 4},
            {"month": "Фев", "value": 4},
            {"month": "Мар", "value": 4},
        ],
        "platform_split": [
            {"name": "Auto.ru", "value": 4},
            {"name": "Avito Авто", "value": 0},
            {"name": "Drom", "value": 0},
        ],
        "analysis": [
            "Hongqi E-HS9 Flagship демонстрирует критически низкое предложение и почти отсутствует за пределами двух столиц.",
            "Полное отсутствие на Avito Авто и Drom указывает на крайне ограниченный канал дистрибуции.",
            "Стабильная цена при малом объёме рынка делает модель интересной для точечного завоза.",
        ],
    },
    {
        "id": "li-auto-mega",
        "brand": "Li Auto",
        "model": "MEGA",
        "full_name": "Li Auto MEGA",
        "year": 2024,
        "platform": "Drom",
        "price": 9_800_000,
        "listings": 2,
        "sellers": 1,
        "regions_count": 1,
        "regions_present": ["Владивосток"],
        "regions_missing": ["Москва", "Санкт-Петербург", *COMMON_MISSING_REGIONS[:12]],
        "competition": "Низкая",
        "deficit": "Высокий",
        "recommendation": "Эксклюзивное предложение",
        "market_share": 0.0008,
        "opportunity_tag": "Эксклюзив",
        "segment": "Эксклюзив",
        "body_type": "Электромобиль",
        "condition": "Новый",
        "price_history": [
            {"month": "Окт", "value": 10.4},
            {"month": "Ноя", "value": 10.1},
            {"month": "Дек", "value": 10.0},
            {"month": "Янв", "value": 9.9},
            {"month": "Фев", "value": 9.8},
            {"month": "Мар", "value": 9.8},
        ],
        "listings_history": [
            {"month": "Окт", "value": 1},
            {"month": "Ноя", "value": 1},
            {"month": "Дек", "value": 2},
            {"month": "Янв", "value": 2},
            {"month": "Фев", "value": 2},
            {"month": "Мар", "value": 2},
        ],
        "platform_split": [
            {"name": "Auto.ru", "value": 0},
            {"name": "Avito Авто", "value": 0},
            {"name": "Drom", "value": 2},
        ],
        "analysis": [
            "Li Auto MEGA присутствует только на Drom и только во Владивостоке, что делает его почти невидимым для центрального рынка.",
            "Для модели нет прямой конкуренции в формате премиального электрического MPV.",
            "Есть потенциал роста при выводе на московский и петербургский рынок.",
        ],
    },
    {
        "id": "rolls-royce-cullinan-black-badge",
        "brand": "Rolls-Royce",
        "model": "Cullinan Black Badge",
        "full_name": "Rolls-Royce Cullinan Black Badge",
        "year": 2024,
        "platform": "Auto.ru",
        "price": 48_500_000,
        "listings": 3,
        "sellers": 2,
        "regions_count": 1,
        "regions_present": ["Москва"],
        "regions_missing": ["Санкт-Петербург", *COMMON_MISSING_REGIONS[:14]],
        "competition": "Низкая",
        "deficit": "Высокий",
        "recommendation": "Уникальное предложение",
        "market_share": 0.0012,
        "opportunity_tag": "Редкая версия",
        "segment": "Люкс",
        "body_type": "Внедорожник",
        "condition": "Новый",
        "price_history": [
            {"month": "Окт", "value": 49.6},
            {"month": "Ноя", "value": 49.2},
            {"month": "Дек", "value": 48.9},
            {"month": "Янв", "value": 48.7},
            {"month": "Фев", "value": 48.5},
            {"month": "Мар", "value": 48.5},
        ],
        "listings_history": [
            {"month": "Окт", "value": 4},
            {"month": "Ноя", "value": 4},
            {"month": "Дек", "value": 4},
            {"month": "Янв", "value": 3},
            {"month": "Фев", "value": 3},
            {"month": "Мар", "value": 3},
        ],
        "platform_split": [
            {"name": "Auto.ru", "value": 3},
            {"name": "Avito Авто", "value": 0},
            {"name": "Drom", "value": 0},
        ],
        "analysis": [
            "Редкая версия Cullinan Black Badge сосредоточена только в Москве и не имеет полноценного предложения в регионах.",
            "Ограниченное число продавцов при высокой цене входа снижает прямую конкуренцию.",
            "Модель подходит для точечной стратегии под эксклюзивный спрос.",
        ],
    },
    {
        "id": "zeekr-009-excellence",
        "brand": "Zeekr",
        "model": "009 Excellence",
        "full_name": "Zeekr 009 Excellence",
        "year": 2024,
        "platform": "Auto.ru",
        "price": 10_200_000,
        "listings": 6,
        "sellers": 4,
        "regions_count": 3,
        "regions_present": ["Москва", "Санкт-Петербург", "Владивосток"],
        "regions_missing": COMMON_MISSING_REGIONS[:15],
        "competition": "Низкая",
        "deficit": "Высокий",
        "recommendation": "Рекомендуется к завозу",
        "market_share": 0.0027,
        "opportunity_tag": "Высокий потенциал",
        "segment": "Премиум",
        "body_type": "Электромобиль",
        "condition": "Новый",
        "price_history": [
            {"month": "Окт", "value": 10.6},
            {"month": "Ноя", "value": 10.5},
            {"month": "Дек", "value": 10.4},
            {"month": "Янв", "value": 10.3},
            {"month": "Фев", "value": 10.2},
            {"month": "Мар", "value": 10.2},
        ],
        "listings_history": [
            {"month": "Окт", "value": 8},
            {"month": "Ноя", "value": 7},
            {"month": "Дек", "value": 7},
            {"month": "Янв", "value": 6},
            {"month": "Фев", "value": 6},
            {"month": "Мар", "value": 6},
        ],
        "platform_split": [
            {"name": "Auto.ru", "value": 4},
            {"name": "Avito Авто", "value": 1},
            {"name": "Drom", "value": 1},
        ],
        "analysis": [
            "Zeekr 009 Excellence уже начинает появляться в нескольких ключевых точках, но остаётся дефицитным.",
            "Спрос поддерживается устойчивой ценой без сильного демпинга.",
            "Есть потенциал для расширения в регионы-миллионники.",
        ],
    },
    {
        "id": "voyah-dream",
        "brand": "Voyah",
        "model": "Dream",
        "full_name": "Voyah Dream",
        "year": 2024,
        "platform": "Auto.ru",
        "price": 8_900_000,
        "listings": 3,
        "sellers": 2,
        "regions_count": 2,
        "regions_present": ["Москва", "Санкт-Петербург"],
        "regions_missing": COMMON_MISSING_REGIONS[:16],
        "competition": "Низкая",
        "deficit": "Высокий",
        "recommendation": "Высокий потенциал",
        "market_share": 0.0011,
        "opportunity_tag": "Дефицитный MPV",
        "segment": "Премиум",
        "body_type": "Гибрид",
        "condition": "До 1 года",
        "price_history": [
            {"month": "Окт", "value": 9.2},
            {"month": "Ноя", "value": 9.1},
            {"month": "Дек", "value": 9.0},
            {"month": "Янв", "value": 8.9},
            {"month": "Фев", "value": 8.9},
            {"month": "Мар", "value": 8.9},
        ],
        "listings_history": [
            {"month": "Окт", "value": 4},
            {"month": "Ноя", "value": 4},
            {"month": "Дек", "value": 3},
            {"month": "Янв", "value": 3},
            {"month": "Фев", "value": 3},
            {"month": "Мар", "value": 3},
        ],
        "platform_split": [
            {"name": "Auto.ru", "value": 2},
            {"name": "Avito Авто", "value": 1},
            {"name": "Drom", "value": 0},
        ],
        "analysis": [
            "Voyah Dream редко встречается в продаже и в основном представлен в столицах.",
            "Модель может занять свою нишу как премиальный семейный гибридный MPV.",
            "Низкое число продавцов создаёт окно для входа без перегрева конкуренции.",
        ],
    },
    {
        "id": "bentley-bentayga-ewb-azure",
        "brand": "Bentley",
        "model": "Bentayga EWB Azure",
        "full_name": "Bentley Bentayga EWB Azure",
        "year": 2024,
        "platform": "Auto.ru",
        "price": 32_900_000,
        "listings": 5,
        "sellers": 3,
        "regions_count": 2,
        "regions_present": ["Москва", "Санкт-Петербург"],
        "regions_missing": COMMON_MISSING_REGIONS[:13],
        "competition": "Низкая",
        "deficit": "Высокий",
        "recommendation": "Эксклюзивная позиция",
        "market_share": 0.0018,
        "opportunity_tag": "Редкая комплектация",
        "segment": "Люкс",
        "body_type": "Внедорожник",
        "condition": "Новый",
        "price_history": [
            {"month": "Окт", "value": 33.8},
            {"month": "Ноя", "value": 33.5},
            {"month": "Дек", "value": 33.3},
            {"month": "Янв", "value": 33.1},
            {"month": "Фев", "value": 32.9},
            {"month": "Мар", "value": 32.9},
        ],
        "listings_history": [
            {"month": "Окт", "value": 6},
            {"month": "Ноя", "value": 6},
            {"month": "Дек", "value": 5},
            {"month": "Янв", "value": 5},
            {"month": "Фев", "value": 5},
            {"month": "Мар", "value": 5},
        ],
        "platform_split": [
            {"name": "Auto.ru", "value": 4},
            {"name": "Avito Авто", "value": 1},
            {"name": "Drom", "value": 0},
        ],
        "analysis": [
            "Bentayga EWB Azure — редкая удлинённая версия, которая появляется точечно и держит цену.",
            "Ограниченное число предложений снижает давление конкурентов.",
            "Подходит для точечной премиальной витрины.",
        ],
    },
    {
        "id": "lamborghini-urus-performante",
        "brand": "Lamborghini",
        "model": "Urus Performante",
        "full_name": "Lamborghini Urus Performante",
        "year": 2024,
        "platform": "Avito Авто",
        "price": 38_700_000,
        "listings": 7,
        "sellers": 5,
        "regions_count": 3,
        "regions_present": ["Москва", "Санкт-Петербург", "Сочи"],
        "regions_missing": COMMON_MISSING_REGIONS[:12],
        "competition": "Средняя",
        "deficit": "Высокий",
        "recommendation": "Следить за спросом",
        "market_share": 0.0031,
        "opportunity_tag": "Редкая спорт-версия",
        "segment": "Спорт",
        "body_type": "Внедорожник",
        "condition": "Новый",
        "price_history": [
            {"month": "Окт", "value": 39.5},
            {"month": "Ноя", "value": 39.2},
            {"month": "Дек", "value": 39.0},
            {"month": "Янв", "value": 38.9},
            {"month": "Фев", "value": 38.7},
            {"month": "Мар", "value": 38.7},
        ],
        "listings_history": [
            {"month": "Окт", "value": 8},
            {"month": "Ноя", "value": 8},
            {"month": "Дек", "value": 7},
            {"month": "Янв", "value": 7},
            {"month": "Фев", "value": 7},
            {"month": "Мар", "value": 7},
        ],
        "platform_split": [
            {"name": "Auto.ru", "value": 2},
            {"name": "Avito Авто", "value": 4},
            {"name": "Drom", "value": 1},
        ],
        "analysis": [
            "Urus Performante остаётся редкой спортивной версией, но уже начинает набирать видимость.",
            "Средняя конкуренция говорит о том, что продавцы заметили нишу, но рынок ещё не насыщен.",
            "Интересен при точном позиционировании и ограниченном объёме ввоза.",
        ],
    },
    {
        "id": "range-rover-sv-carmel-edition",
        "brand": "Range Rover",
        "model": "SV Carmel Edition",
        "full_name": "Range Rover SV Carmel Edition",
        "year": 2024,
        "platform": "Auto.ru",
        "price": 21_500_000,
        "listings": 4,
        "sellers": 2,
        "regions_count": 2,
        "regions_present": ["Москва", "Сочи"],
        "regions_missing": COMMON_MISSING_REGIONS[:12],
        "competition": "Низкая",
        "deficit": "Высокий",
        "recommendation": "Редкая лимитированная серия",
        "market_share": 0.0015,
        "opportunity_tag": "Лимитированная серия",
        "segment": "Люкс",
        "body_type": "Внедорожник",
        "condition": "Новый",
        "price_history": [
            {"month": "Окт", "value": 22.1},
            {"month": "Ноя", "value": 21.9},
            {"month": "Дек", "value": 21.8},
            {"month": "Янв", "value": 21.7},
            {"month": "Фев", "value": 21.5},
            {"month": "Мар", "value": 21.5},
        ],
        "listings_history": [
            {"month": "Окт", "value": 5},
            {"month": "Ноя", "value": 5},
            {"month": "Дек", "value": 4},
            {"month": "Янв", "value": 4},
            {"month": "Фев", "value": 4},
            {"month": "Мар", "value": 4},
        ],
        "platform_split": [
            {"name": "Auto.ru", "value": 4},
            {"name": "Avito Авто", "value": 0},
            {"name": "Drom", "value": 0},
        ],
        "analysis": [
            "SV Carmel Edition — лимитированная серия, которую рынок видит крайне редко.",
            "Представленность только на одной платформе усиливает дефицит.",
            "Хороший кандидат для эксклюзивного предложения без прямого сравнения по массе объявлений.",
        ],
    },
    {
        "id": "mercedes-benz-eqs-580-amg",
        "brand": "Mercedes-Benz",
        "model": "EQS 580 AMG",
        "full_name": "Mercedes-Benz EQS 580 AMG",
        "year": 2024,
        "platform": "Auto.ru",
        "price": 14_200_000,
        "listings": 8,
        "sellers": 6,
        "regions_count": 4,
        "regions_present": ["Москва", "Санкт-Петербург", "Казань", "Сочи"],
        "regions_missing": COMMON_MISSING_REGIONS[3:14],
        "competition": "Средняя",
        "deficit": "Средний",
        "recommendation": "Наблюдать",
        "market_share": 0.0042,
        "opportunity_tag": "Редкий электролюкс",
        "segment": "Премиум",
        "body_type": "Электромобиль",
        "condition": "До 1 года",
        "price_history": [
            {"month": "Окт", "value": 14.9},
            {"month": "Ноя", "value": 14.8},
            {"month": "Дек", "value": 14.6},
            {"month": "Янв", "value": 14.4},
            {"month": "Фев", "value": 14.3},
            {"month": "Мар", "value": 14.2},
        ],
        "listings_history": [
            {"month": "Окт", "value": 9},
            {"month": "Ноя", "value": 9},
            {"month": "Дек", "value": 8},
            {"month": "Янв", "value": 8},
            {"month": "Фев", "value": 8},
            {"month": "Мар", "value": 8},
        ],
        "platform_split": [
            {"name": "Auto.ru", "value": 5},
            {"name": "Avito Авто", "value": 2},
            {"name": "Drom", "value": 1},
        ],
        "analysis": [
            "EQS 580 AMG остаётся редким на фоне массовых S-классов и GLS, но уже заметен на рынке.",
            "Конкуренция не критична, однако ниша постепенно насыщается.",
            "Подходит для избирательного подхода и контроля цены входа.",
        ],
    },
    {
        "id": "porsche-taycan-turbo-s-cross-turismo",
        "brand": "Porsche",
        "model": "Taycan Turbo S Cross Turismo",
        "full_name": "Porsche Taycan Turbo S Cross Turismo",
        "year": 2024,
        "platform": "Avito Авто",
        "price": 16_800_000,
        "listings": 5,
        "sellers": 4,
        "regions_count": 3,
        "regions_present": ["Москва", "Санкт-Петербург", "Краснодар"],
        "regions_missing": COMMON_MISSING_REGIONS[1:13],
        "competition": "Низкая",
        "deficit": "Высокий",
        "recommendation": "Редкий формат кузова",
        "market_share": 0.0022,
        "opportunity_tag": "Нишевая электричка",
        "segment": "Спорт",
        "body_type": "Электромобиль",
        "condition": "До 1 года",
        "price_history": [
            {"month": "Окт", "value": 17.4},
            {"month": "Ноя", "value": 17.2},
            {"month": "Дек", "value": 17.0},
            {"month": "Янв", "value": 16.9},
            {"month": "Фев", "value": 16.8},
            {"month": "Мар", "value": 16.8},
        ],
        "listings_history": [
            {"month": "Окт", "value": 6},
            {"month": "Ноя", "value": 6},
            {"month": "Дек", "value": 5},
            {"month": "Янв", "value": 5},
            {"month": "Фев", "value": 5},
            {"month": "Мар", "value": 5},
        ],
        "platform_split": [
            {"name": "Auto.ru", "value": 1},
            {"name": "Avito Авто", "value": 3},
            {"name": "Drom", "value": 1},
        ],
        "analysis": [
            "Cross Turismo заметно реже обычного Taycan и удерживает более эксклюзивное позиционирование.",
            "Низкая конкуренция и редкий кузов делают модель интересной для узкой аудитории.",
            "Может хорошо работать в подборке для клиентов, которые ищут неочевидный Porsche.",
        ],
    },
    {
        "id": "bmw-ix-m60",
        "brand": "BMW",
        "model": "iX M60",
        "full_name": "BMW iX M60",
        "year": 2024,
        "platform": "Auto.ru",
        "price": 13_500_000,
        "listings": 9,
        "sellers": 7,
        "regions_count": 4,
        "regions_present": ["Москва", "Санкт-Петербург", "Екатеринбург", "Казань"],
        "regions_missing": COMMON_MISSING_REGIONS[4:14],
        "competition": "Средняя",
        "deficit": "Средний",
        "recommendation": "Контролируемая ниша",
        "market_share": 0.0048,
        "opportunity_tag": "Редкий BMW EV",
        "segment": "Премиум",
        "body_type": "Электромобиль",
        "condition": "До 1 года",
        "price_history": [
            {"month": "Окт", "value": 14.0},
            {"month": "Ноя", "value": 13.9},
            {"month": "Дек", "value": 13.8},
            {"month": "Янв", "value": 13.7},
            {"month": "Фев", "value": 13.6},
            {"month": "Мар", "value": 13.5},
        ],
        "listings_history": [
            {"month": "Окт", "value": 10},
            {"month": "Ноя", "value": 10},
            {"month": "Дек", "value": 9},
            {"month": "Янв", "value": 9},
            {"month": "Фев", "value": 9},
            {"month": "Мар", "value": 9},
        ],
        "platform_split": [
            {"name": "Auto.ru", "value": 6},
            {"name": "Avito Авто", "value": 2},
            {"name": "Drom", "value": 1},
        ],
        "analysis": [
            "BMW iX M60 уже заметен в крупных городах, но всё ещё остаётся редким для своего класса.",
            "Рынок не перегрет, однако динамика указывает на постепенное расширение предложения.",
            "Подходит для стратегии осторожного расширения.",
        ],
    },
    {
        "id": "audi-e-tron-gt-rs",
        "brand": "Audi",
        "model": "e-tron GT RS",
        "full_name": "Audi e-tron GT RS",
        "year": 2024,
        "platform": "Drom",
        "price": 15_900_000,
        "listings": 4,
        "sellers": 3,
        "regions_count": 2,
        "regions_present": ["Владивосток", "Хабаровск"],
        "regions_missing": ["Москва", "Санкт-Петербург", *COMMON_MISSING_REGIONS[:10]],
        "competition": "Низкая",
        "deficit": "Высокий",
        "recommendation": "Региональная редкость",
        "market_share": 0.0014,
        "opportunity_tag": "Недопредставлен в центре",
        "segment": "Спорт",
        "body_type": "Электромобиль",
        "condition": "До 1 года",
        "price_history": [
            {"month": "Окт", "value": 16.5},
            {"month": "Ноя", "value": 16.3},
            {"month": "Дек", "value": 16.1},
            {"month": "Янв", "value": 16.0},
            {"month": "Фев", "value": 15.9},
            {"month": "Мар", "value": 15.9},
        ],
        "listings_history": [
            {"month": "Окт", "value": 5},
            {"month": "Ноя", "value": 5},
            {"month": "Дек", "value": 4},
            {"month": "Янв", "value": 4},
            {"month": "Фев", "value": 4},
            {"month": "Мар", "value": 4},
        ],
        "platform_split": [
            {"name": "Auto.ru", "value": 1},
            {"name": "Avito Авто", "value": 0},
            {"name": "Drom", "value": 3},
        ],
        "analysis": [
            "e-tron GT RS сейчас выглядит региональной редкостью с уклоном в Дальний Восток.",
            "Слабое присутствие в Москве и Санкт-Петербурге создаёт окно для выхода на центральный рынок.",
            "Подходит для стратегии вывода дефицитной спортивной электромодели.",
        ],
    },
    {
        "id": "lexus-lx-600-ultra-luxury",
        "brand": "Lexus",
        "model": "LX 600 Ultra Luxury",
        "full_name": "Lexus LX 600 Ultra Luxury",
        "year": 2024,
        "platform": "Auto.ru",
        "price": 17_200_000,
        "listings": 11,
        "sellers": 8,
        "regions_count": 5,
        "regions_present": ["Москва", "Санкт-Петербург", "Казань", "Сочи", "Екатеринбург"],
        "regions_missing": COMMON_MISSING_REGIONS[5:12],
        "competition": "Средняя",
        "deficit": "Средний",
        "recommendation": "Выбирать точечно",
        "market_share": 0.0053,
        "opportunity_tag": "Редкая комплектация",
        "segment": "Люкс",
        "body_type": "Внедорожник",
        "condition": "Новый",
        "price_history": [
            {"month": "Окт", "value": 17.8},
            {"month": "Ноя", "value": 17.6},
            {"month": "Дек", "value": 17.5},
            {"month": "Янв", "value": 17.4},
            {"month": "Фев", "value": 17.3},
            {"month": "Мар", "value": 17.2},
        ],
        "listings_history": [
            {"month": "Окт", "value": 12},
            {"month": "Ноя", "value": 12},
            {"month": "Дек", "value": 11},
            {"month": "Янв", "value": 11},
            {"month": "Фев", "value": 11},
            {"month": "Мар", "value": 11},
        ],
        "platform_split": [
            {"name": "Auto.ru", "value": 7},
            {"name": "Avito Авто", "value": 3},
            {"name": "Drom", "value": 1},
        ],
        "analysis": [
            "Ultra Luxury встречается реже стандартного LX 600 и пока не образует плотного конкурентного поля.",
            "В крупных городах предложение уже есть, но рынок ещё далёк от насыщения.",
            "Хороший кандидат для точечного предложения под статусную аудиторию.",
        ],
    },
    {
        "id": "genesis-g90-3-5t-awd",
        "brand": "Genesis",
        "model": "G90 3.5T AWD",
        "full_name": "Genesis G90 3.5T AWD",
        "year": 2024,
        "platform": "Avito Авто",
        "price": 8_700_000,
        "listings": 6,
        "sellers": 4,
        "regions_count": 3,
        "regions_present": ["Москва", "Санкт-Петербург", "Краснодар"],
        "regions_missing": COMMON_MISSING_REGIONS[2:12],
        "competition": "Низкая",
        "deficit": "Высокий",
        "recommendation": "Недооценённый седан",
        "market_share": 0.0026,
        "opportunity_tag": "Мало конкурентов",
        "segment": "Премиум",
        "body_type": "Седан",
        "condition": "Новый",
        "price_history": [
            {"month": "Окт", "value": 9.1},
            {"month": "Ноя", "value": 9.0},
            {"month": "Дек", "value": 8.9},
            {"month": "Янв", "value": 8.8},
            {"month": "Фев", "value": 8.7},
            {"month": "Мар", "value": 8.7},
        ],
        "listings_history": [
            {"month": "Окт", "value": 7},
            {"month": "Ноя", "value": 7},
            {"month": "Дек", "value": 6},
            {"month": "Янв", "value": 6},
            {"month": "Фев", "value": 6},
            {"month": "Мар", "value": 6},
        ],
        "platform_split": [
            {"name": "Auto.ru", "value": 2},
            {"name": "Avito Авто", "value": 3},
            {"name": "Drom", "value": 1},
        ],
        "analysis": [
            "Genesis G90 3.5T AWD остаётся недооценённой альтернативой немецким флагманским седанам.",
            "Низкая конкуренция сочетается с понятным позиционированием по цене.",
            "Может давать хорошее окно входа при правильной комплектации.",
        ],
    },
    {
        "id": "land-rover-defender-130-v8",
        "brand": "Land Rover",
        "model": "Defender 130 V8",
        "full_name": "Land Rover Defender 130 V8",
        "year": 2024,
        "platform": "Auto.ru",
        "price": 14_800_000,
        "listings": 7,
        "sellers": 5,
        "regions_count": 4,
        "regions_present": ["Москва", "Санкт-Петербург", "Сочи", "Екатеринбург"],
        "regions_missing": COMMON_MISSING_REGIONS[6:13],
        "competition": "Средняя",
        "deficit": "Средний",
        "recommendation": "Следить за точкой входа",
        "market_share": 0.0033,
        "opportunity_tag": "Редкая мощная версия",
        "segment": "Премиум",
        "body_type": "Внедорожник",
        "condition": "Новый",
        "price_history": [
            {"month": "Окт", "value": 15.2},
            {"month": "Ноя", "value": 15.1},
            {"month": "Дек", "value": 15.0},
            {"month": "Янв", "value": 14.9},
            {"month": "Фев", "value": 14.8},
            {"month": "Мар", "value": 14.8},
        ],
        "listings_history": [
            {"month": "Окт", "value": 8},
            {"month": "Ноя", "value": 8},
            {"month": "Дек", "value": 7},
            {"month": "Янв", "value": 7},
            {"month": "Фев", "value": 7},
            {"month": "Мар", "value": 7},
        ],
        "platform_split": [
            {"name": "Auto.ru", "value": 5},
            {"name": "Avito Авто", "value": 1},
            {"name": "Drom", "value": 1},
        ],
        "analysis": [
            "Defender 130 V8 встречается редко даже среди дорогих внедорожников и хорошо выделяется на фоне стандартных версий.",
            "Конкуренция контролируемая, но уже не нулевая.",
            "Требует аккуратного подбора по конфигурации и цене.",
        ],
    },
]

PLATFORMS = [
    {
        "id": "Auto.ru",
        "total_listings": 287_450,
        "new_cars": 42_340,
        "under_one_year": 98_230,
        "rare_models": 512,
        "avg_price": 3_500_000,
        "regions": [
            {"name": "Москва", "value": 168_200},
            {"name": "Санкт-Петербург", "value": 54_100},
            {"name": "Регионы", "value": 65_150},
        ],
        "top_brands": ["Mercedes-Benz", "BMW", "Toyota", "Lexus", "Porsche"],
        "commentary": "Доминирующая платформа с массовым предложением. Среди сотен тысяч объявлений выявлено всего 512 редких моделей.",
    },
    {
        "id": "Avito Авто",
        "total_listings": 192_380,
        "new_cars": 28_700,
        "under_one_year": 67_800,
        "rare_models": 328,
        "avg_price": 2_800_000,
        "regions": [
            {"name": "Москва", "value": 72_000},
            {"name": "Санкт-Петербург", "value": 38_200},
            {"name": "Регионы", "value": 82_180},
        ],
        "top_brands": ["Toyota", "BMW", "Mercedes-Benz", "Kia", "Range Rover"],
        "commentary": "Массовый вторичный рынок. Из почти 200 тысяч объявлений только 328 редких эксклюзивных моделей.",
    },
    {
        "id": "Drom",
        "total_listings": 44_017,
        "new_cars": 6_980,
        "under_one_year": 15_280,
        "rare_models": 167,
        "avg_price": 2_200_000,
        "regions": [
            {"name": "Москва", "value": 8_400},
            {"name": "Санкт-Петербург", "value": 4_500},
            {"name": "Регионы", "value": 31_117},
        ],
        "top_brands": ["Toyota", "Lexus", "Audi", "Li Auto", "Zeekr"],
        "commentary": "Региональная платформа с фокусом на Дальний Восток. Среди 44 тысяч объявлений найдено 167 редких моделей.",
    },
]

REGIONS = [
    {
        "id": "Москва",
        "total_listings": 214_500,
        "avg_price": 5_800_000,
        "competition": "Высокая",
        "popular_models": ["Toyota Land Cruiser 300", "Mercedes-Benz GLE", "BMW X7"],
        "deficit_models": ["Li Auto MEGA", "Hongqi E-HS9 Flagship", "Audi e-tron GT RS"],
        "recommendation": "Рынок Москвы самый ликвидный, но для редких машин всё ещё есть окна. Логично выводить модели с нулевым или слабым присутствием на Auto.ru и Avito.",
    },
    {
        "id": "Санкт-Петербург",
        "total_listings": 67_800,
        "avg_price": 4_900_000,
        "competition": "Средняя",
        "popular_models": ["Mercedes-Benz GLS", "BMW X5", "Lexus LX"],
        "deficit_models": ["Range Rover SV Carmel Edition", "Voyah Dream", "Li Auto MEGA"],
        "recommendation": "Санкт-Петербург хорошо подходит для редких премиальных моделей со стабильной ценой и малым количеством конкурентов.",
    },
    {
        "id": "Владивосток",
        "total_listings": 31_400,
        "avg_price": 3_600_000,
        "competition": "Средняя",
        "popular_models": ["Toyota Land Cruiser Prado", "Lexus RX", "Toyota Alphard"],
        "deficit_models": ["Rolls-Royce Cullinan Black Badge", "Bentley Bentayga EWB Azure", "Genesis G90 3.5T AWD"],
        "recommendation": "Регион даёт хороший поток по новым брендам и электромобилям, но люкс-сегмент здесь уже требует более точечной стратегии.",
    },
]

MARKET_OPPORTUNITIES = [
    {
        "id": "hongqi-e-hs9-flagship",
        "type": "Критический дефицит",
        "brand": "Hongqi",
        "model": "E-HS9 Flagship",
        "description": "Всего 4 объявления на рынке, почти весь объём сосредоточен в столицах.",
        "potential": "Высокий",
    },
    {
        "id": "li-auto-mega",
        "type": "Эксклюзив",
        "brand": "Li Auto",
        "model": "MEGA",
        "description": "2 объявления и полное отсутствие на Auto.ru и Avito Авто.",
        "potential": "Высокий",
    },
    {
        "id": "rolls-royce-cullinan-black-badge",
        "type": "Редкая версия",
        "brand": "Rolls-Royce",
        "model": "Cullinan Black Badge",
        "description": "3 объявления только в Москве, минимальная конкуренция.",
        "potential": "Высокий",
    },
    {
        "id": "audi-e-tron-gt-rs",
        "type": "Платформенный перекос",
        "brand": "Audi",
        "model": "e-tron GT RS",
        "description": "Почти весь объём на Drom, слабое присутствие в центральных каналах.",
        "potential": "Высокий",
    },
]
